# GitHub Actions Workflow for updating README.md file after running Python script

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
      - cron: "0 0 */1 * *"  # Runs every day at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
    
    - name: Run Update Python Script
      run: |
        python main.py
    
    - name: Update README.md file
      run: | 
        git add README.md  # Only add README.md
        git config --local user.email "hyunwoo.kim1108@gmail.com"
        git config --local user.name "nomoreFt"
        git commit -m "Update README.md"
        git push
